import {
  Award,
  Star,
  Heart,
  Globe,
  Shield,
  Headphones,
  Map,
  Plane,
  Ship,
  Clock,
  Users,
  CheckCircle,
  TrendingUp,
  Zap,
  Target,
  ThumbsUp,
  Compass,
  Anchor,
  Briefcase,
  Camera,
  Coffee,
  Gift,
  Home,
  Key,
  Lightbulb,
  MessageCircle,
  Phone,
  Settings,
  Smile,
  Sun,
  Umbrella,
  Wifi,
  type LucideIcon,
} from "lucide-react";

export const iconMap: Record<string, LucideIcon> = {
  award: Award,
  star: Star,
  heart: Heart,
  globe: Globe,
  shield: Shield,
  headphones: Headphones,
  map: Map,
  plane: Plane,
  ship: Ship,
  clock: Clock,
  users: Users,
  "check-circle": CheckCircle,
  "trending-up": TrendingUp,
  zap: Zap,
  target: Target,
  "thumbs-up": ThumbsUp,
  compass: Compass,
  anchor: Anchor,
  briefcase: Briefcase,
  camera: Camera,
  coffee: Coffee,
  gift: Gift,
  home: Home,
  key: Key,
  lightbulb: Lightbulb,
  "message-circle": MessageCircle,
  phone: Phone,
  settings: Settings,
  smile: Smile,
  sun: Sun,
  umbrella: Umbrella,
  wifi: Wifi,
};

export const getIconComponent = (name: string): LucideIcon => {
  return iconMap[name?.toLowerCase()] || Award;
};
